// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CallExtensionData, CallExtensionErrors, CallExtensionResponses, ContainerLogsData, ContainerLogsErrors, ContainerLogsResponses, ContainerStatsData, ContainerStatsErrors, ContainerStatsResponses, EditFileData, EditFileErrors, EditFileResponses, EngineInfoData, EngineInfoResponses, ExecCommandData, ExecCommandErrors, ExecCommandResponses, GetSettingsData, GetSettingsErrors, GetSettingsResponses, GlobFilesData, GlobFilesErrors, GlobFilesResponses, GrepFilesData, GrepFilesErrors, GrepFilesResponses, InspectContainerData, InspectContainerErrors, InspectContainerResponses, InspectImageData, InspectImageErrors, InspectImageResponses, ListAllContainersData, ListAllContainersErrors, ListAllContainersResponses, ListDirData, ListDirErrors, ListDirResponses, ListExtensionsData, ListExtensionsErrors, ListExtensionsResponses, ListImagesData, ListImagesResponses, ListNetworksData, ListNetworksResponses, ListProcessesData, ListProcessesErrors, ListProcessesResponses, ListVolumesData, ListVolumesResponses, ProxyRequestData, ProxyRequestErrors, ProxyRequestResponses, PutSettingsData, PutSettingsErrors, PutSettingsResponses, ReadFileData, ReadFileErrors, ReadFileResponses, RemoveContainerData, RemoveContainerErrors, RemoveContainerResponses, RemoveImageData, RemoveImageErrors, RemoveImageResponses, RemoveNetworkData, RemoveNetworkErrors, RemoveNetworkResponses, RemoveVolumeData, RemoveVolumeErrors, RemoveVolumeResponses, RestartContainerData, RestartContainerErrors, RestartContainerResponses, StartContainerData, StartContainerErrors, StartContainerResponses, StopContainerData, StopContainerErrors, StopContainerResponses, SystemInfoData, SystemInfoErrors, SystemInfoResponses, WriteFileData, WriteFileErrors, WriteFileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const listAllContainers = <ThrowOnError extends boolean = false>(options?: Options<ListAllContainersData, ThrowOnError>) => (options?.client ?? client).get<ListAllContainersResponses, ListAllContainersErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers',
    ...options
});

export const engineInfo = <ThrowOnError extends boolean = false>(options?: Options<EngineInfoData, ThrowOnError>) => (options?.client ?? client).get<EngineInfoResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/engine',
    ...options
});

export const listImages = <ThrowOnError extends boolean = false>(options?: Options<ListImagesData, ThrowOnError>) => (options?.client ?? client).get<ListImagesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/images',
    ...options
});

export const removeImage = <ThrowOnError extends boolean = false>(options: Options<RemoveImageData, ThrowOnError>) => (options.client ?? client).delete<RemoveImageResponses, RemoveImageErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/images/{id}',
    ...options
});

export const inspectImage = <ThrowOnError extends boolean = false>(options: Options<InspectImageData, ThrowOnError>) => (options.client ?? client).get<InspectImageResponses, InspectImageErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/images/{id}',
    ...options
});

export const listNetworks = <ThrowOnError extends boolean = false>(options?: Options<ListNetworksData, ThrowOnError>) => (options?.client ?? client).get<ListNetworksResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/networks',
    ...options
});

export const removeNetwork = <ThrowOnError extends boolean = false>(options: Options<RemoveNetworkData, ThrowOnError>) => (options.client ?? client).delete<RemoveNetworkResponses, RemoveNetworkErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/networks/{id}',
    ...options
});

export const listVolumes = <ThrowOnError extends boolean = false>(options?: Options<ListVolumesData, ThrowOnError>) => (options?.client ?? client).get<ListVolumesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/volumes',
    ...options
});

export const removeVolume = <ThrowOnError extends boolean = false>(options: Options<RemoveVolumeData, ThrowOnError>) => (options.client ?? client).delete<RemoveVolumeResponses, RemoveVolumeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/volumes/{name}',
    ...options
});

export const removeContainer = <ThrowOnError extends boolean = false>(options: Options<RemoveContainerData, ThrowOnError>) => (options.client ?? client).delete<RemoveContainerResponses, RemoveContainerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/{id}',
    ...options
});

export const inspectContainer = <ThrowOnError extends boolean = false>(options: Options<InspectContainerData, ThrowOnError>) => (options.client ?? client).get<InspectContainerResponses, InspectContainerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/{id}',
    ...options
});

export const containerLogs = <ThrowOnError extends boolean = false>(options: Options<ContainerLogsData, ThrowOnError>) => (options.client ?? client).get<ContainerLogsResponses, ContainerLogsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/{id}/logs',
    ...options
});

export const restartContainer = <ThrowOnError extends boolean = false>(options: Options<RestartContainerData, ThrowOnError>) => (options.client ?? client).post<RestartContainerResponses, RestartContainerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/{id}/restart',
    ...options
});

export const startContainer = <ThrowOnError extends boolean = false>(options: Options<StartContainerData, ThrowOnError>) => (options.client ?? client).post<StartContainerResponses, StartContainerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/{id}/start',
    ...options
});

export const containerStats = <ThrowOnError extends boolean = false>(options: Options<ContainerStatsData, ThrowOnError>) => (options.client ?? client).get<ContainerStatsResponses, ContainerStatsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/{id}/stats',
    ...options
});

export const stopContainer = <ThrowOnError extends boolean = false>(options: Options<StopContainerData, ThrowOnError>) => (options.client ?? client).post<StopContainerResponses, StopContainerErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/containers/{id}/stop',
    ...options
});

/**
 * List extensions declared by the calling plugin.
 *
 * Only returns extensions the plugin declared in its manifest `"extensions"` field.
 * Includes availability status (is it installed and running?) and per-operation
 * permission status. Plugins cannot see extensions they didn't declare.
 */
export const listExtensions = <ThrowOnError extends boolean = false>(options?: Options<ListExtensionsData, ThrowOnError>) => (options?.client ?? client).get<ListExtensionsResponses, ListExtensionsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/extensions',
    ...options
});

/**
 * Execute an extension operation.
 *
 * Three-layer security model:
 * 1. PERMISSION: Does this plugin have `ext:{ext_id}:{operation}`?
 * 2. SCOPE: If the operation declares `scope_key`, is the scope value approved?
 * 3. RISK: If risk_level is high, per-invocation runtime approval.
 */
export const callExtension = <ThrowOnError extends boolean = false>(options: Options<CallExtensionData, ThrowOnError>) => (options.client ?? client).post<CallExtensionResponses, CallExtensionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/extensions/{ext_id}/{operation}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const editFile = <ThrowOnError extends boolean = false>(options: Options<EditFileData, ThrowOnError>) => (options.client ?? client).post<EditFileResponses, EditFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/fs/edit',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const globFiles = <ThrowOnError extends boolean = false>(options: Options<GlobFilesData, ThrowOnError>) => (options.client ?? client).get<GlobFilesResponses, GlobFilesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/fs/glob',
    ...options
});

export const grepFiles = <ThrowOnError extends boolean = false>(options: Options<GrepFilesData, ThrowOnError>) => (options.client ?? client).get<GrepFilesResponses, GrepFilesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/fs/grep',
    ...options
});

export const listDir = <ThrowOnError extends boolean = false>(options: Options<ListDirData, ThrowOnError>) => (options.client ?? client).get<ListDirResponses, ListDirErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/fs/list',
    ...options
});

export const readFile = <ThrowOnError extends boolean = false>(options: Options<ReadFileData, ThrowOnError>) => (options.client ?? client).get<ReadFileResponses, ReadFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/fs/read',
    ...options
});

export const writeFile = <ThrowOnError extends boolean = false>(options: Options<WriteFileData, ThrowOnError>) => (options.client ?? client).post<WriteFileResponses, WriteFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/fs/write',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const proxyRequest = <ThrowOnError extends boolean = false>(options: Options<ProxyRequestData, ThrowOnError>) => (options.client ?? client).post<ProxyRequestResponses, ProxyRequestErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/network/proxy',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const execCommand = <ThrowOnError extends boolean = false>(options: Options<ExecCommandData, ThrowOnError>) => (options.client ?? client).post<ExecCommandResponses, ExecCommandErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/process/exec',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const listProcesses = <ThrowOnError extends boolean = false>(options?: Options<ListProcessesData, ThrowOnError>) => (options?.client ?? client).get<ListProcessesResponses, ListProcessesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/process/list',
    ...options
});

/**
 * Get settings for the authenticated plugin.
 *
 * Returns a flat key-value map. Defaults from the manifest are
 * applied first, then any explicitly saved overrides.
 */
export const getSettings = <ThrowOnError extends boolean = false>(options?: Options<GetSettingsData, ThrowOnError>) => (options?.client ?? client).get<GetSettingsResponses, GetSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/settings',
    ...options
});

/**
 * Update settings for the authenticated plugin.
 *
 * Accepts a flat key-value map. Values are validated against the manifest's
 * settings schema: unknown keys are rejected, value types must match.
 */
export const putSettings = <ThrowOnError extends boolean = false>(options: Options<PutSettingsData, ThrowOnError>) => (options.client ?? client).put<PutSettingsResponses, PutSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/settings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const systemInfo = <ThrowOnError extends boolean = false>(options?: Options<SystemInfoData, ThrowOnError>) => (options?.client ?? client).get<SystemInfoResponses, SystemInfoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/system/info',
    ...options
});
