// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Request body for POST /v1/extensions/{ext_id}/{operation}
 */
export type CallExtensionRequest = {
    input?: unknown;
};

/**
 * Response for POST /v1/extensions/{ext_id}/{operation}
 */
export type CallExtensionResponse = {
    data: unknown;
    message?: string | null;
    success: boolean;
};

export type ContainerInfo = {
    id: string;
    image: string;
    names: Array<string>;
    state: string;
    status: string;
};

export type ContainerLogs = {
    lines: Array<string>;
};

export type DirEntry = {
    is_dir: boolean;
    name: string;
    path: string;
    size: number;
};

export type DirListing = {
    entries: Array<DirEntry>;
    path: string;
};

export type EditRequest = {
    new_string: string;
    old_string: string;
    path: string;
    replace_all?: boolean;
};

export type EngineInfo = {
    arch?: string | null;
    cpus?: number | null;
    engine_id: string;
    memory_bytes?: number | null;
    os?: string | null;
    version?: string | null;
};

export type ExecRequest = {
    /**
     * Arguments to pass to the command
     */
    args?: Array<string>;
    /**
     * The command to execute (e.g. "git", "cargo", "ls")
     */
    command: string;
    /**
     * Timeout in seconds (default: 30, max: 600)
     */
    timeout_secs?: number | null;
    /**
     * Working directory (must be absolute). Defaults to home directory.
     */
    working_dir?: string | null;
};

export type ExecResult = {
    exit_code?: number | null;
    stderr: string;
    stdout: string;
    /**
     * Whether the command was killed due to timeout
     */
    timed_out: boolean;
};

/**
 * Error response body
 */
export type ExtensionErrorResponse = {
    details?: string | null;
    error: string;
};

export type FileContent = {
    content: string;
    path: string;
    size: number;
};

export type GlobResult = {
    base_path: string;
    matches: Array<string>;
    pattern: string;
};

export type GrepFileMatch = {
    lines: Array<GrepLine>;
    path: string;
};

export type GrepLine = {
    content: string;
    /**
     * Whether this line is a context line (vs a direct match)
     */
    is_context: boolean;
    line_number: number;
};

export type GrepResult = {
    matches: Array<GrepFileMatch>;
    pattern: string;
    search_path: string;
};

export type ImageInfo = {
    created: number;
    id: string;
    repo_tags: Array<string>;
    size: number;
};

/**
 * Response for GET /v1/extensions
 */
export type ListExtensionsResponse = {
    extensions: Array<PluginExtensionView>;
};

export type NetworkInfo = {
    driver: string;
    id: string;
    name: string;
    scope: string;
};

/**
 * A plugin's view of an extension it declared as a dependency.
 */
export type PluginExtensionView = {
    available: boolean;
    description?: string | null;
    display_name?: string | null;
    id: string;
    operations: Array<PluginOperationView>;
};

/**
 * A plugin's view of an operation on a declared extension.
 */
export type PluginOperationView = {
    available: boolean;
    name: string;
    permitted: boolean;
};

export type ProcessInfo = {
    cpu_usage: number;
    memory: number;
    name: string;
    pid: number;
};

export type ProxyRequest = {
    body?: string | null;
    headers?: {
        [key: string]: string;
    };
    method: string;
    url: string;
};

export type ProxyResponse = {
    body: string;
    headers: {
        [key: string]: string;
    };
    status: number;
};

export type StatusMessage = {
    status: string;
};

export type SystemInfo = {
    cpu_count: number;
    hostname: string;
    nexus_version: string;
    os: string;
    os_version: string;
    total_memory: number;
    uptime: number;
};

export type VolumeInfo = {
    created_at?: string | null;
    driver: string;
    mountpoint: string;
    name: string;
};

export type WriteRequest = {
    content: string;
    path: string;
};

export type ListAllContainersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/containers';
};

export type ListAllContainersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ListAllContainersResponses = {
    /**
     * All containers
     */
    200: Array<ContainerInfo>;
};

export type ListAllContainersResponse = ListAllContainersResponses[keyof ListAllContainersResponses];

export type EngineInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/containers/engine';
};

export type EngineInfoResponses = {
    /**
     * Container engine info
     */
    200: EngineInfo;
};

export type EngineInfoResponse = EngineInfoResponses[keyof EngineInfoResponses];

export type ListImagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/containers/images';
};

export type ListImagesResponses = {
    /**
     * All images
     */
    200: Array<ImageInfo>;
};

export type ListImagesResponse = ListImagesResponses[keyof ListImagesResponses];

export type RemoveImageData = {
    body?: never;
    path: {
        /**
         * Image ID or name:tag
         */
        id: string;
    };
    query?: {
        /**
         * Force remove (default: false)
         */
        force?: boolean;
    };
    url: '/api/v1/containers/images/{id}';
};

export type RemoveImageErrors = {
    /**
     * Image not found
     */
    404: unknown;
};

export type RemoveImageResponses = {
    /**
     * Image removed
     */
    200: StatusMessage;
};

export type RemoveImageResponse = RemoveImageResponses[keyof RemoveImageResponses];

export type InspectImageData = {
    body?: never;
    path: {
        /**
         * Image ID or name:tag
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/containers/images/{id}';
};

export type InspectImageErrors = {
    /**
     * Image not found
     */
    404: unknown;
};

export type InspectImageResponses = {
    /**
     * Image inspect
     */
    200: {
        [key: string]: unknown;
    };
};

export type InspectImageResponse = InspectImageResponses[keyof InspectImageResponses];

export type ListNetworksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/containers/networks';
};

export type ListNetworksResponses = {
    /**
     * All networks
     */
    200: Array<NetworkInfo>;
};

export type ListNetworksResponse = ListNetworksResponses[keyof ListNetworksResponses];

export type RemoveNetworkData = {
    body?: never;
    path: {
        /**
         * Network ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/containers/networks/{id}';
};

export type RemoveNetworkErrors = {
    /**
     * Network not found
     */
    404: unknown;
};

export type RemoveNetworkResponses = {
    /**
     * Network removed
     */
    200: StatusMessage;
};

export type RemoveNetworkResponse = RemoveNetworkResponses[keyof RemoveNetworkResponses];

export type ListVolumesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/containers/volumes';
};

export type ListVolumesResponses = {
    /**
     * All volumes
     */
    200: Array<VolumeInfo>;
};

export type ListVolumesResponse = ListVolumesResponses[keyof ListVolumesResponses];

export type RemoveVolumeData = {
    body?: never;
    path: {
        /**
         * Volume name
         */
        name: string;
    };
    query?: never;
    url: '/api/v1/containers/volumes/{name}';
};

export type RemoveVolumeErrors = {
    /**
     * Volume not found
     */
    404: unknown;
};

export type RemoveVolumeResponses = {
    /**
     * Volume removed
     */
    200: StatusMessage;
};

export type RemoveVolumeResponse = RemoveVolumeResponses[keyof RemoveVolumeResponses];

export type RemoveContainerData = {
    body?: never;
    path: {
        /**
         * Container ID or name
         */
        id: string;
    };
    query?: {
        /**
         * Force remove (default: false)
         */
        force?: boolean;
    };
    url: '/api/v1/containers/{id}';
};

export type RemoveContainerErrors = {
    /**
     * Container not found
     */
    404: unknown;
};

export type RemoveContainerResponses = {
    /**
     * Container removed
     */
    200: StatusMessage;
};

export type RemoveContainerResponse = RemoveContainerResponses[keyof RemoveContainerResponses];

export type InspectContainerData = {
    body?: never;
    path: {
        /**
         * Container ID or name
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/containers/{id}';
};

export type InspectContainerErrors = {
    /**
     * Container not found
     */
    404: unknown;
};

export type InspectContainerResponses = {
    /**
     * Container inspect
     */
    200: {
        [key: string]: unknown;
    };
};

export type InspectContainerResponse = InspectContainerResponses[keyof InspectContainerResponses];

export type ContainerLogsData = {
    body?: never;
    path: {
        /**
         * Container ID or name
         */
        id: string;
    };
    query?: {
        /**
         * Number of lines to return (default: 100)
         */
        tail?: number;
    };
    url: '/api/v1/containers/{id}/logs';
};

export type ContainerLogsErrors = {
    /**
     * Container not found
     */
    404: unknown;
};

export type ContainerLogsResponses = {
    /**
     * Container logs
     */
    200: ContainerLogs;
};

export type ContainerLogsResponse = ContainerLogsResponses[keyof ContainerLogsResponses];

export type RestartContainerData = {
    body?: never;
    path: {
        /**
         * Container ID or name
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/containers/{id}/restart';
};

export type RestartContainerErrors = {
    /**
     * Container not found
     */
    404: unknown;
};

export type RestartContainerResponses = {
    /**
     * Container restarted
     */
    200: StatusMessage;
};

export type RestartContainerResponse = RestartContainerResponses[keyof RestartContainerResponses];

export type StartContainerData = {
    body?: never;
    path: {
        /**
         * Container ID or name
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/containers/{id}/start';
};

export type StartContainerErrors = {
    /**
     * Container not found
     */
    404: unknown;
};

export type StartContainerResponses = {
    /**
     * Container started
     */
    200: StatusMessage;
};

export type StartContainerResponse = StartContainerResponses[keyof StartContainerResponses];

export type ContainerStatsData = {
    body?: never;
    path: {
        /**
         * Container ID or name
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/containers/{id}/stats';
};

export type ContainerStatsErrors = {
    /**
     * Container not found
     */
    404: unknown;
};

export type ContainerStatsResponses = {
    /**
     * One-shot container stats
     */
    200: {
        [key: string]: unknown;
    };
};

export type ContainerStatsResponse = ContainerStatsResponses[keyof ContainerStatsResponses];

export type StopContainerData = {
    body?: never;
    path: {
        /**
         * Container ID or name
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/containers/{id}/stop';
};

export type StopContainerErrors = {
    /**
     * Container not found
     */
    404: unknown;
};

export type StopContainerResponses = {
    /**
     * Container stopped
     */
    200: StatusMessage;
};

export type StopContainerResponse = StopContainerResponses[keyof StopContainerResponses];

export type ListExtensionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/extensions';
};

export type ListExtensionsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ListExtensionsResponses = {
    /**
     * Extensions declared by this plugin
     */
    200: ListExtensionsResponse;
};

export type ListExtensionsResponse2 = ListExtensionsResponses[keyof ListExtensionsResponses];

export type CallExtensionData = {
    body: CallExtensionRequest;
    path: {
        /**
         * Extension ID
         */
        ext_id: string;
        /**
         * Operation name
         */
        operation: string;
    };
    query?: never;
    url: '/api/v1/extensions/{ext_id}/{operation}';
};

export type CallExtensionErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden — extension not found, missing permission, or scope denied
     */
    403: unknown;
};

export type CallExtensionResponses = {
    /**
     * Operation result
     */
    200: CallExtensionResponse;
};

export type CallExtensionResponse2 = CallExtensionResponses[keyof CallExtensionResponses];

export type EditFileData = {
    body: EditRequest;
    path?: never;
    query?: never;
    url: '/api/v1/fs/edit';
};

export type EditFileErrors = {
    /**
     * old_string not found or not unique
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type EditFileResponses = {
    /**
     * File edited
     */
    200: unknown;
};

export type GlobFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Glob pattern (e.g. "***.ts", "src***.rs")
         */
        pattern: string;
        /**
         * Base directory to search from (must be absolute)
         */
        path: string;
    };
    url: '/api/v1/fs/glob';
};

export type GlobFilesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GlobFilesResponses = {
    /**
     * Matching files
     */
    200: GlobResult;
};

export type GlobFilesResponse = GlobFilesResponses[keyof GlobFilesResponses];

export type GrepFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Regex pattern to search for
         */
        pattern: string;
        /**
         * File or directory to search in (must be absolute)
         */
        path: string;
        /**
         * Optional glob filter for file names (e.g. "*.ts")
         */
        include?: string | null;
        /**
         * Number of context lines around matches (default: 0)
         */
        context_lines?: number | null;
        /**
         * Maximum number of matching files to return (default: 50)
         */
        max_results?: number | null;
    };
    url: '/api/v1/fs/grep';
};

export type GrepFilesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GrepFilesResponses = {
    /**
     * Search results
     */
    200: GrepResult;
};

export type GrepFilesResponse = GrepFilesResponses[keyof GrepFilesResponses];

export type ListDirData = {
    body?: never;
    path?: never;
    query: {
        path: string;
    };
    url: '/api/v1/fs/list';
};

export type ListDirErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ListDirResponses = {
    /**
     * Directory listing
     */
    200: DirListing;
};

export type ListDirResponse = ListDirResponses[keyof ListDirResponses];

export type ReadFileData = {
    body?: never;
    path?: never;
    query: {
        path: string;
    };
    url: '/api/v1/fs/read';
};

export type ReadFileErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ReadFileResponses = {
    /**
     * File content
     */
    200: FileContent;
};

export type ReadFileResponse = ReadFileResponses[keyof ReadFileResponses];

export type WriteFileData = {
    body: WriteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/fs/write';
};

export type WriteFileErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type WriteFileResponses = {
    /**
     * File written
     */
    200: unknown;
};

export type ProxyRequestData = {
    body: ProxyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/network/proxy';
};

export type ProxyRequestErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Upstream error
     */
    502: unknown;
};

export type ProxyRequestResponses = {
    /**
     * Proxied response
     */
    200: ProxyResponse;
};

export type ProxyRequestResponse = ProxyRequestResponses[keyof ProxyRequestResponses];

export type ExecCommandData = {
    body: ExecRequest;
    path?: never;
    query?: never;
    url: '/api/v1/process/exec';
};

export type ExecCommandErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ExecCommandResponses = {
    /**
     * Command output
     */
    200: ExecResult;
};

export type ExecCommandResponse = ExecCommandResponses[keyof ExecCommandResponses];

export type ListProcessesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/process/list';
};

export type ListProcessesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Permission denied
     */
    403: unknown;
};

export type ListProcessesResponses = {
    /**
     * Running processes
     */
    200: Array<ProcessInfo>;
};

export type ListProcessesResponse = ListProcessesResponses[keyof ListProcessesResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * Plugin settings
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type PutSettingsData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/settings';
};

export type PutSettingsErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type PutSettingsResponses = {
    /**
     * Settings saved
     */
    200: unknown;
};

export type SystemInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/info';
};

export type SystemInfoErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type SystemInfoResponses = {
    /**
     * Host system information
     */
    200: SystemInfo;
};

export type SystemInfoResponse = SystemInfoResponses[keyof SystemInfoResponses];
