// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Request body for POST /v1/extensions/{ext_id}/{operation}
 */
export type CallExtensionRequest = {
    input?: unknown;
};

/**
 * Response for POST /v1/extensions/{ext_id}/{operation}
 */
export type CallExtensionResponse = {
    data: unknown;
    message?: string | null;
    success: boolean;
};

export type ContainerInfo = {
    id: string;
    image: string;
    names: Array<string>;
    state: string;
    status: string;
};

export type DirEntry = {
    is_dir: boolean;
    name: string;
    path: string;
    size: number;
};

export type DirListing = {
    entries: Array<DirEntry>;
    path: string;
};

export type EditRequest = {
    new_string: string;
    old_string: string;
    path: string;
    replace_all?: boolean;
};

export type ExecRequest = {
    /**
     * Arguments to pass to the command
     */
    args?: Array<string>;
    /**
     * The command to execute (e.g. "git", "cargo", "ls")
     */
    command: string;
    /**
     * Timeout in seconds (default: 30, max: 600)
     */
    timeout_secs?: number | null;
    /**
     * Working directory (must be absolute). Defaults to home directory.
     */
    working_dir?: string | null;
};

export type ExecResult = {
    exit_code?: number | null;
    stderr: string;
    stdout: string;
    /**
     * Whether the command was killed due to timeout
     */
    timed_out: boolean;
};

/**
 * Error response body
 */
export type ExtensionErrorResponse = {
    details?: string | null;
    error: string;
};

export type FileContent = {
    content: string;
    path: string;
    size: number;
};

export type GlobResult = {
    base_path: string;
    matches: Array<string>;
    pattern: string;
};

export type GrepFileMatch = {
    lines: Array<GrepLine>;
    path: string;
};

export type GrepLine = {
    content: string;
    /**
     * Whether this line is a context line (vs a direct match)
     */
    is_context: boolean;
    line_number: number;
};

export type GrepResult = {
    matches: Array<GrepFileMatch>;
    pattern: string;
    search_path: string;
};

/**
 * Response for GET /v1/extensions
 */
export type ListExtensionsResponse = {
    extensions: Array<PluginExtensionView>;
};

/**
 * A plugin's view of an extension it declared as a dependency.
 */
export type PluginExtensionView = {
    available: boolean;
    description?: string | null;
    display_name?: string | null;
    id: string;
    operations: Array<PluginOperationView>;
};

/**
 * A plugin's view of an operation on a declared extension.
 */
export type PluginOperationView = {
    available: boolean;
    name: string;
    permitted: boolean;
};

export type ProcessInfo = {
    cpu_usage: number;
    memory: number;
    name: string;
    pid: number;
};

export type ProxyRequest = {
    body?: string | null;
    headers?: {
        [key: string]: string;
    };
    method: string;
    url: string;
};

export type ProxyResponse = {
    body: string;
    headers: {
        [key: string]: string;
    };
    status: number;
};

export type SystemInfo = {
    cpu_count: number;
    hostname: string;
    nexus_version: string;
    os: string;
    os_version: string;
    total_memory: number;
    uptime: number;
};

export type WriteRequest = {
    content: string;
    path: string;
};

export type ListContainersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/docker/containers';
};

export type ListContainersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ListContainersResponses = {
    /**
     * Docker containers
     */
    200: Array<ContainerInfo>;
};

export type ListContainersResponse = ListContainersResponses[keyof ListContainersResponses];

export type ContainerStatsData = {
    body?: never;
    path: {
        /**
         * Container ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/docker/stats/{id}';
};

export type ContainerStatsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ContainerStatsResponses = {
    /**
     * Container stats (Docker inspect)
     */
    200: {
        [key: string]: unknown;
    };
};

export type ContainerStatsResponse = ContainerStatsResponses[keyof ContainerStatsResponses];

export type ListExtensionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/extensions';
};

export type ListExtensionsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type ListExtensionsResponses = {
    /**
     * Extensions declared by this plugin
     */
    200: ListExtensionsResponse;
};

export type ListExtensionsResponse2 = ListExtensionsResponses[keyof ListExtensionsResponses];

export type CallExtensionData = {
    body: CallExtensionRequest;
    path: {
        /**
         * Extension ID
         */
        ext_id: string;
        /**
         * Operation name
         */
        operation: string;
    };
    query?: never;
    url: '/api/v1/extensions/{ext_id}/{operation}';
};

export type CallExtensionErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden — extension not found, missing permission, or scope denied
     */
    403: unknown;
};

export type CallExtensionResponses = {
    /**
     * Operation result
     */
    200: CallExtensionResponse;
};

export type CallExtensionResponse2 = CallExtensionResponses[keyof CallExtensionResponses];

export type EditFileData = {
    body: EditRequest;
    path?: never;
    query?: never;
    url: '/api/v1/fs/edit';
};

export type EditFileErrors = {
    /**
     * old_string not found or not unique
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type EditFileResponses = {
    /**
     * File edited
     */
    200: unknown;
};

export type GlobFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Glob pattern (e.g. "***.ts", "src***.rs")
         */
        pattern: string;
        /**
         * Base directory to search from (must be absolute)
         */
        path: string;
    };
    url: '/api/v1/fs/glob';
};

export type GlobFilesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GlobFilesResponses = {
    /**
     * Matching files
     */
    200: GlobResult;
};

export type GlobFilesResponse = GlobFilesResponses[keyof GlobFilesResponses];

export type GrepFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Regex pattern to search for
         */
        pattern: string;
        /**
         * File or directory to search in (must be absolute)
         */
        path: string;
        /**
         * Optional glob filter for file names (e.g. "*.ts")
         */
        include?: string | null;
        /**
         * Number of context lines around matches (default: 0)
         */
        context_lines?: number | null;
        /**
         * Maximum number of matching files to return (default: 50)
         */
        max_results?: number | null;
    };
    url: '/api/v1/fs/grep';
};

export type GrepFilesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type GrepFilesResponses = {
    /**
     * Search results
     */
    200: GrepResult;
};

export type GrepFilesResponse = GrepFilesResponses[keyof GrepFilesResponses];

export type ListDirData = {
    body?: never;
    path?: never;
    query: {
        path: string;
    };
    url: '/api/v1/fs/list';
};

export type ListDirErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ListDirResponses = {
    /**
     * Directory listing
     */
    200: DirListing;
};

export type ListDirResponse = ListDirResponses[keyof ListDirResponses];

export type ReadFileData = {
    body?: never;
    path?: never;
    query: {
        path: string;
    };
    url: '/api/v1/fs/read';
};

export type ReadFileErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ReadFileResponses = {
    /**
     * File content
     */
    200: FileContent;
};

export type ReadFileResponse = ReadFileResponses[keyof ReadFileResponses];

export type WriteFileData = {
    body: WriteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/fs/write';
};

export type WriteFileErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type WriteFileResponses = {
    /**
     * File written
     */
    200: unknown;
};

export type ProxyRequestData = {
    body: ProxyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/network/proxy';
};

export type ProxyRequestErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Upstream error
     */
    502: unknown;
};

export type ProxyRequestResponses = {
    /**
     * Proxied response
     */
    200: ProxyResponse;
};

export type ProxyRequestResponse = ProxyRequestResponses[keyof ProxyRequestResponses];

export type ExecCommandData = {
    body: ExecRequest;
    path?: never;
    query?: never;
    url: '/api/v1/process/exec';
};

export type ExecCommandErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ExecCommandResponses = {
    /**
     * Command output
     */
    200: ExecResult;
};

export type ExecCommandResponse = ExecCommandResponses[keyof ExecCommandResponses];

export type ListProcessesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/process/list';
};

export type ListProcessesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Permission denied
     */
    403: unknown;
};

export type ListProcessesResponses = {
    /**
     * Running processes
     */
    200: Array<ProcessInfo>;
};

export type ListProcessesResponse = ListProcessesResponses[keyof ListProcessesResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * Plugin settings
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type PutSettingsData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/settings';
};

export type PutSettingsErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type PutSettingsResponses = {
    /**
     * Settings saved
     */
    200: unknown;
};

export type SystemInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/info';
};

export type SystemInfoErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type SystemInfoResponses = {
    /**
     * Host system information
     */
    200: SystemInfo;
};

export type SystemInfoResponse = SystemInfoResponses[keyof SystemInfoResponses];
