// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ContainerInfo = {
    id: string;
    image: string;
    names: Array<string>;
    state: string;
    status: string;
};

export type DirEntry = {
    is_dir: boolean;
    name: string;
    path: string;
    size: number;
};

export type DirListing = {
    entries: Array<DirEntry>;
    path: string;
};

export type FileContent = {
    content: string;
    path: string;
    size: number;
};

export type ProcessInfo = {
    cpu_usage: number;
    memory: number;
    name: string;
    pid: number;
};

export type ProxyRequest = {
    body?: string | null;
    headers?: {
        [key: string]: string;
    };
    method: string;
    url: string;
};

export type ProxyResponse = {
    body: string;
    headers: {
        [key: string]: string;
    };
    status: number;
};

export type SystemInfo = {
    cpu_count: number;
    hostname: string;
    nexus_version: string;
    os: string;
    os_version: string;
    total_memory: number;
    uptime: number;
};

export type WriteRequest = {
    content: string;
    path: string;
};

export type ListContainersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/docker/containers';
};

export type ListContainersErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ListContainersResponses = {
    /**
     * Docker containers
     */
    200: Array<ContainerInfo>;
};

export type ListContainersResponse = ListContainersResponses[keyof ListContainersResponses];

export type ContainerStatsData = {
    body?: never;
    path: {
        /**
         * Container ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/docker/stats/{id}';
};

export type ContainerStatsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ContainerStatsResponses = {
    /**
     * Container stats (Docker inspect)
     */
    200: {
        [key: string]: unknown;
    };
};

export type ContainerStatsResponse = ContainerStatsResponses[keyof ContainerStatsResponses];

export type ListDirData = {
    body?: never;
    path?: never;
    query: {
        path: string;
    };
    url: '/api/v1/fs/list';
};

export type ListDirErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ListDirResponses = {
    /**
     * Directory listing
     */
    200: DirListing;
};

export type ListDirResponse = ListDirResponses[keyof ListDirResponses];

export type ReadFileData = {
    body?: never;
    path?: never;
    query: {
        path: string;
    };
    url: '/api/v1/fs/read';
};

export type ReadFileErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ReadFileResponses = {
    /**
     * File content
     */
    200: FileContent;
};

export type ReadFileResponse = ReadFileResponses[keyof ReadFileResponses];

export type WriteFileData = {
    body: WriteRequest;
    path?: never;
    query?: never;
    url: '/api/v1/fs/write';
};

export type WriteFileErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type WriteFileResponses = {
    /**
     * File written
     */
    200: unknown;
};

export type ProxyRequestData = {
    body: ProxyRequest;
    path?: never;
    query?: never;
    url: '/api/v1/network/proxy';
};

export type ProxyRequestErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Upstream error
     */
    502: unknown;
};

export type ProxyRequestResponses = {
    /**
     * Proxied response
     */
    200: ProxyResponse;
};

export type ProxyRequestResponse = ProxyRequestResponses[keyof ProxyRequestResponses];

export type ListProcessesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/process/list';
};

export type ListProcessesErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Permission denied
     */
    403: unknown;
};

export type ListProcessesResponses = {
    /**
     * Running processes
     */
    200: Array<ProcessInfo>;
};

export type ListProcessesResponse = ListProcessesResponses[keyof ListProcessesResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * Plugin settings
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type PutSettingsData = {
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/settings';
};

export type PutSettingsErrors = {
    /**
     * Validation error
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
};

export type PutSettingsResponses = {
    /**
     * Settings saved
     */
    200: unknown;
};

export type SystemInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/system/info';
};

export type SystemInfoErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type SystemInfoResponses = {
    /**
     * Host system information
     */
    200: SystemInfo;
};

export type SystemInfoResponse = SystemInfoResponses[keyof SystemInfoResponses];
